### ISSUE TITLE
New way to add question

### ISSUE THREAD

**Issue by kacimimoghite** [TSaaP/tsaap-notes#155]
### Description

As a teacher 
I want to access a real preview of an edited question
So that I don't have to check the result at the of the list of questions

### Acceptance tests

_Given_
A teacher accessing the question page of a scope

_Then_
On the top of the page an "Add question" button is displayed (no more hidden editor)

_When_
The teacher clicks on the add button
_then_ 
the popup window containing the question editor appears (with preview button and so on)

_When_ 
The teacher type a new question with a picture associated
_and_
the teacher clicks on the preview button
_then_
a real preview of the resulted question is displayed (respecting width, height, picture display and so on)

_When_
The teacher clicks on the add button in question editor
_Then_
The question is added at the end of the question list
_And_
There is a message (feedback) saying the question was added at the top of the page

### Tasks

- [x] Remove hidden editor
- [x] Display the real preview
- [x] Add feedback when the question is added
