### ISSUE TITLE
Simplification of question edition/ creation 

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#180]
## Description

_As a_ 
teacher,
_I want to_ 
specify only informations relative to the question and no more informations relative to the process,
_So that_ 
the creation/edition of a question is more effective and the choice of the process is delayed to the execution of the quizz

## Acceptation tests

_Given_
an authenticated teacher editing a new or existing question

_Then_
the form provides fields to specify only:
- the title,
- the statement
- the interaction type
     - open ended (students provide atextual response)
     - choice interaction
          - the choice type (multiple or exclusive)
          - the number of items
          - the selection of items corresponding to the good response

<img width="884" alt="capture d ecran 2017-02-22 a 15 10 59" src="https://cloud.githubusercontent.com/assets/1417089/23215043/3f80997c-f911-11e6-8c09-ba25d45f5334.png">

## Technical hints
All these informations specify completely  a question, they should be stored in the same entity/table.
A field "interactionType" and another "interactionSpecification" should be added to the statement/entity.
Json format of the "interactionSpecification" in case of choice interaction
{
     "expectedChoiceList: [{"index":2,"score":100.0}],
     "choiceInteractionType":"EXCLUSIVE",
      "itemCount":2
}

## Tasks

- [x] add a new field in statement entity to store the question specification (items, etc.)
- [x] update service layer on sequence and statement management
- [x] update controller ?
- [x] update the edition form
