### ISSUE TITLE
Update of a note (or a question) after it has been created and posted 

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#45]
### Description
As an author of a note (that can be a question)
I want to update my note after I inserted it
So that I can correct some mistakes on the posted note

### Acceptance tests

_Given_ 
a user 
_and_ 
a note posted by this user and noteTaking is enabled on the scope
_then_
the interface provide the user a link "Edit" near the other links for a given notes ( _reply_, _delete_, etc.).

_When_
The user clicks on the "Edit" link,
_then_
A popup windows appears containing the form allowing the user to modify the content of the note (or the form for the question if it is a question).
_and_ 
the form contains a "Cancel" link and a "Save" button.

_When_
The user clicks on the "Cancel" link, it closes the popup window.

_When_
The user clicks on the "Save" button, it closes the popup window and it refreshes the content of the modified note or question on the main page.

_Given_
A user author of a note linked with an image
_When_
The user clicks on the X on the image
_Then_
The image is unlinked (deleted) from the note

_Given_
A user author of a note linked with a file (not an image)
_When_
The user clicks on the X next to the file link
_Then_
The file is unlinked (deleted) from the note

_Given_
A user author of a note without attachment
_When_
The user clicks on the edit link on the note
_Then_
An edition modal is shown
_When_
The user choose a file and then update the note
_Then_
The file is correctly added and linked to the note

### Tasks
- [x] Modify existing (or create) views and controller methods
- [x] Manage attachments
- [x] Modify question template so the wrapper is not in it
- [x] formRemote (AJAX) to remove attachments
- [x] Can't edit if takingNote disabled (can edit questions though)
- [x] Can't edit question when started

**Comment by Minizarbi** [comment]
We have to add security checks
