### ISSUE TITLE
Tsaap-Notes as LTI Provider

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#76]
### Description

As a user logged in a LTI consumer (Moodle for exemple)
I want to get an authenticated access to Tsaap-Notes  directly from a link in the LTI consumer
So that I don't have to logg-in explicitly in Tsaap-Notes and so that I don't have to find the scope relative to the consumer link.

### Task
- [x] Implementation LTI protocol in Tsaap-Notes based on open source available implementation
- [x] Implementation of the dynamic automatic creation and mapping of Tsaap-User / LTI Consumer User 
- [x] Implementation of the dynamic automatic creation and mapping of Tsaap-Scope and LTI consumer context

### Acceptance tests

*Given*
a teacher authenticated in a Moodle instance supporting LTI modules 
and a link to tsaap-notes in a Moodle course added by the teacher

*When* 
the teacher clicks on the tsaap-notes links for the first time
*Then*
A new account in tsaap-notes is created for the teacher
*and*
a scope corresponding to the course and the activity in Moodle is created in tsaap-notes
*and*
the teacher is authenticated in Tsaap-Notes
*and* 
he accesses directly to the page of notes corresponding to the created scope
